#!/bin/bash
# Grit conversion script for IsometricBold font atlas
# Generated by ttf_to_atlas.py

GRIT=/opt/wonderful/thirdparty/blocksds/core/tools/grit/grit

# Convert font atlas to NDS format
# -gt: generate tiles
# -gB8: 8bpp tiles
# -mR!: NO tile reduction (critical for fonts! we need direct char->tile mapping)
# -mLf: flat map layout (linear tile indices)
# -p: generate palette
# -gT000000: transparent color (magenta)
# -ftb: output as binary files

$GRIT IsometricBold.png -gt -gB8 -mR! -mLf -p -gT000000 -ftb

# Rename outputs to standard naming
mv IsometricBold.img.bin IsometricBold_tiles.bin
# No map file needed - we calculate indices directly
rm -f IsometricBold.map.bin 2>/dev/null
mv IsometricBold.pal.bin IsometricBold_pal.bin

echo "Converted IsometricBold font atlas"
echo "Output files:"
echo "  IsometricBold_tiles.bin - Tile graphics (linear, no reduction)"
echo "  IsometricBold_pal.bin   - Palette"
