#!/bin/bash
# Grit conversion script for PeaberryBase font atlas
# Generated by ttf_to_atlas.py

GRIT=/opt/wonderful/thirdparty/blocksds/core/tools/grit/grit

# Convert font atlas to NDS format
# -gt: generate tiles
# -gB8: 8bpp tiles
# -mR!: NO tile reduction (critical for fonts! we need direct char->tile mapping)
# -mLf: flat map layout (linear tile indices)
# -p: generate palette
# -gTFFFFFF: transparent color (magenta)
# -ftb: output as binary files

$GRIT PeaberryBase.png -gt -gB8 -mR! -mLf -p -gTFFFFFF -ftb

# Rename outputs to standard naming
mv PeaberryBase.img.bin PeaberryBase_tiles.bin
# No map file needed - we calculate indices directly
rm -f PeaberryBase.map.bin 2>/dev/null
mv PeaberryBase.pal.bin PeaberryBase_pal.bin

echo "Converted PeaberryBase font atlas"
echo "Output files:"
echo "  PeaberryBase_tiles.bin - Tile graphics (linear, no reduction)"
echo "  PeaberryBase_pal.bin   - Palette"
